### ISSUE TITLE
Porting to different languages

### ISSUE THREAD

**Issue by ZeronSix** [tomdalling/opengl-series#3]
These articles are perfect. The bad thing is that source code is C++/Obj-C only. But C++ is not the only language that can be used with OpenGL. Personally i wrote a C# port which is located [here](https://github.com/ZeronSix/opengl-series-csharp). It would be nice to add a link to it to the README.md of this repo. If someone has a Java, Python, etc.. port, he should post a link here too.

**Comment by tomdalling** [comment]
I just realised that this is still an open issue. Thanks for the port!
