### ISSUE TITLE
glUseProgram for each render is not necessary

### ISSUE THREAD

**Issue by LangdalP** [tomdalling/opengl-series#5]
I'm currently only at article 3, but after glancing over the last article this practice seems to persist:
Using glUseProgram(shaderID) before rendering, and then using glUseProgram(0) afterwards, for each iteration. I thought this was weird and tried to refactor your code in article 3 so that gProgram->use() is called before the main loop, and gProgram->stopUsing() is called after.

This does not break the behaviour of the program so I then continued on to ##OpenGL on freenode IRC and asked what was considered good practice. A user named Bloodlust told me that "Langdal the preferred way is to never unbind", and that you should only call glUseProgram whenever you are setting or changing shader programs. Furthermore, installing and uninstalling (I'm not sure what the correct terminology is here) the shader program for each render operation introduces unnecessary overhead.

I just wanted to let you know in case you did not know this.

**Comment by tomdalling** [comment]
Thanks for commenting. The binding and unbinding is intentional. I wanted to show all of the necessary steps in a single place. I'm trying to optimise the code for ease of learning, instead of performance. We might look at performance optimisation in a later article.
