### ISSUE TITLE
ERROR LNK2001/2019 sln

### ISSUE THREAD

**Issue by CZWin32768** [tomdalling/opengl-series#8]
When I built the sln, I got "glfw3.lib(context.c.obj) : error LNK2019: unresolved external symbol __imp__sscanf referenced in function _parseVersionString".

Then I found the solution in the stackoverflow: You can also add an additional library to your linker input i.e, legacy_stdio_definitions.lib

Go to Properties > Linker > Input.

**Comment by tomdalling** [comment]
Thanks for reporting this.

This is on Windows, right? Could you tell me what version of Visual Studio you're using?

I'm trying to get VS 2015, but something is really wrong with my Windows machine and it won't install. I'll look into it as soon as I can get VS working.

**Comment by Mateos81** [comment]
This may help you: https://www.visualstudio.com/en-us/downloads/visual-studio-2015-system-requirements-vs.aspx#1

Perhaps a missing KB?

**Comment by CZWin32768** [comment]
I'm using the Visual Studio 2015 Community. After I add the legacy_stdio_definitions.lib to the Linker, it worked. Thanks for your tutorials and source codes. It really helps! Maybe I need to install the Update 2 of VS. The VS is so big that maybe I'll never install it again!

**Comment by tomdalling** [comment]
The project was made in VS 2013, and VS 2015 has some differences that broke the build. I finally got VS 2015 installed, updated the project, and added `legacy_stdio_definitions.lib`. It should be all good until VS 2017 come out now.

Thanks again!
